import { BsFiletypeHtml } from "react-icons/bs";
export  const TechstackList = [
    {
        _id:1,
        name:'HTML',
        icon:BsFiletypeHtml
    },
    {
        _id:2,
        name:'CSS',
        icon:BsFiletypeHtml
    },
    {
        _id:3,
        name:'Javascript',
        icon:BsFiletypeHtml
    },
    {
        _id:4,
        name:'MongoDB',
        icon:BsFiletypeHtml
    },
    {
        _id:5,
        name:'React',
        icon:BsFiletypeHtml
    },
    {
        _id:6,
        name:'Express',
        icon:BsFiletypeHtml
    },
    {
        _id:7,
        name:'NodeJS',
        icon:BsFiletypeHtml
    },
    {
        _id:8,
        name:'C++',
        icon:BsFiletypeHtml
    },
    {
        _id:9,
        name:'Python',
        icon:BsFiletypeHtml
    },
    {
        _id:10,
        name:'MySQL',
        icon:BsFiletypeHtml
    }
]